# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-08 03:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20170608_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
