# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-08 05:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20170608_1102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='sutype',
            new_name='subtype',
        ),
    ]
