# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-19 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20170619_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, default='', help_text='Describe yourself with 500 characters or less. There will be no formatting.', max_length=1000, verbose_name='biography'),
        ),
    ]
