# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-21 17:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20170621_2329'),
        ('users', '0007_auto_20170621_1948'),
    ]

    operations = [
    ]
