# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-20 09:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diary', '0017_auto_20170620_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.CharField(blank=True, max_length=80, null=True)),
                ('img', models.FileField(upload_to='user_media/')),
                ('diary', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='diary.Diary')),
            ],
        ),
    ]
