# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-20 12:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Media',
        ),
    ]
