# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-06 04:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_auto_20170604_2117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diary',
            name='userID',
        ),
    ]
