# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-06 07:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0004_diary_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
