# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-10 06:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0008_auto_20170609_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='type',
            field=models.CharField(choices=[('私密', 'S'), ('公開', 'P')], default='私密', max_length=30),
        ),
    ]
