# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-10 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0010_auto_20170610_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='type',
            field=models.CharField(choices=[(0, '私密'), (1, '公開')], default=0, max_length=30),
        ),
    ]
