# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-10 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0011_auto_20170610_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='type',
            field=models.CharField(choices=[('Private', '私密'), ('Public', '公開')], default='Private', max_length=30),
        ),
    ]
