# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-11 08:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0013_auto_20170611_0055'),
        ('diary', '0010_auto_20170610_1906'),
    ]

    operations = [
    ]
