# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-11 16:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0014_merge_20170611_1613'),
        ('diary', '0009_auto_20170610_1903'),
    ]

    operations = [
    ]
