# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-20 08:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0016_auto_20170612_0005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='diary',
        ),
        migrations.DeleteModel(
            name='Media',
        ),
    ]
