# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-20 18:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diary', '0017_auto_20170620_1659'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diary',
            old_name='type',
            new_name='post_type',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='tagName',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='diary',
            name='userID',
        ),
        migrations.AddField(
            model_name='diary',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='diary',
            name='content',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='diary',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='diary',
            name='tags',
            field=models.ManyToManyField(blank=True, to='diary.Tag'),
        ),
        migrations.AlterField(
            model_name='diary',
            name='weather_cond',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='diary',
            name='weather_meantemp',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True),
        ),
    ]
