# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-21 00:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0018_auto_20170621_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='diary',
            name='weather_cond',
            field=models.CharField(blank=True, default='null', editable=False, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='diary',
            name='weather_meantemp',
            field=models.CharField(blank=True, default='null', editable=False, max_length=50, null=True),
        ),
    ]
