# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-21 04:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0019_auto_20170621_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='weather_cond',
            field=models.CharField(blank=True, default='', editable=False, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='diary',
            name='weather_meantemp',
            field=models.CharField(blank=True, default='', editable=False, max_length=50, null=True),
        ),
    ]
