# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-15 04:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tally',
            name='pay_type',
            field=models.CharField(choices=[('Income', '收入'), ('Expenses', '支出')], default='Income', max_length=20),
        ),
        migrations.AlterField(
            model_name='tally',
            name='type',
            field=models.CharField(choices=[('Food', '食物'), ('Fun', '玩樂'), ('Traffic', '交通'), ('Other', '其他')], default='Other', max_length=20),
        ),
    ]
