# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-15 04:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0003_auto_20170615_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tally',
            name='pay_type',
            field=models.CharField(choices=[('收入', '收入'), ('支出', '支出')], default='收入', max_length=20),
        ),
        migrations.AlterField(
            model_name='tally',
            name='type',
            field=models.CharField(choices=[('食物', '食物'), ('玩樂', '玩樂'), ('交通', '交通'), ('其他', '其他')], default='其他', max_length=20),
        ),
    ]
