# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-15 06:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tally', '0004_auto_20170615_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='tally',
            name='userID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
