# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-15 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0005_tally_userid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tally',
            options={'ordering': ['date']},
        ),
        migrations.AlterField(
            model_name='tally',
            name='type',
            field=models.CharField(choices=[('食物', '食物'), ('玩樂', '玩樂'), ('交通', '交通'), ('薪資', '薪資'), ('其他', '其他')], default='其他', max_length=20),
        ),
    ]
