# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-19 02:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0007_auto_20170615_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tally',
            name='pay_type',
            field=models.CharField(choices=[('收入', ('收入', 'fdfd')), ('支出', ('支出', 'dslfjdf'))], default='收入', max_length=20),
        ),
    ]
