# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-19 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0009_auto_20170619_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tally',
            name='type',
            field=models.CharField(choices=[('收入', '收入'), ('支出', '支出')], max_length=20),
        ),
    ]
