# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-19 03:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0010_auto_20170619_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tally',
            name='pay_type',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='tally',
            name='type',
            field=models.CharField(max_length=20),
        ),
    ]
