# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-19 03:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0011_auto_20170619_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tally',
            name='type',
            field=models.CharField(choices=[('Income', (('Job', 'Job'),)), ('Pay', (('Fun', 'Fun'), ('PPPP', 'PPP')))], max_length=20),
        ),
    ]
