# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-19 03:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0012_auto_20170619_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tally',
            name='pay_type',
        ),
    ]
