# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-20 05:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0015_auto_20170619_1155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tally',
            old_name='price',
            new_name='cash',
        ),
        migrations.RenameField(
            model_name='tally',
            old_name='userID',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='tally',
            name='type',
        ),
        migrations.AddField(
            model_name='tally',
            name='pay_type',
            field=models.CharField(choices=[('Income', (('Part-time Job', 'Part-time Job'), ('Pocket Money', 'Pocket Money'), ('Other incomes', 'Other incomes'))), ('Expense', (('Food', 'Food'), ('Entertainment', 'Entertainment'), ('Traffic', 'Traffic'), ('Other expenses', 'Other expenses')))], default='Food', max_length=20),
        ),
    ]
