# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-20 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0016_auto_20170620_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tally',
            name='notes',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='tally',
            name='subtype',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
